### ISSUE TITLE
Yoshua Bengio's slides link is broken on the website

### ISSUE THREAD

**Issue by hindupuravinash** [autodiff-workshop/autodiff-workshop.github.io#3]
Yoshua Bengio's slides link is broken at https://autodiff-workshop.github.io/. I guess it's because of the difference in file name. 
Rest all of the files are named after the speaker but this particular file is named: `YoshuaBengio-NIPSAutoDiffWorkshop10dec2016.key.pdf`

**Comment by nouiz** [comment]
In case github didn't sent a notification, this was fixed.

thanks for the report.
